
# ===== Nodes default =====
# == Used for canopen_motor_node, previously declared ==

defaults: # optional, all defaults can be overwritten per node
  # canopen_chain_node settings ..
  motor_allocator: canopen::Motor402::Allocator # select allocator for motor layer
  motor_layer: # settings passed to motor layer (plugin-specific)
    switching_state: 3 # (Operation_Enable), state for mode switching | It may be 4
  
  publish: ["1001", "60FF", "6060", "6040", "605B", "6041"] # Objects to read
  # pos_to_device: "rint(rad2deg(pos)*1000)" # rad -> mdeg
  # pos_from_device: "deg2rad(obj6064)/1000" # actual position [mdeg] -> rad
  # vel_to_device: "rint(rad2deg(vel)*1000)" # rad/s -> mdeg/s
  # vel_from_device: "deg2rad(obj606C)/1000" # actual velocity [mdeg/s] -> rad/s
  # eff_to_device: "rint(eff)" # just round to integer
  # eff_from_device: "0" # unset

# ===== Node Layer =====
nodes:
  node1:
    name: motorRight
    id: 1
    eds_file: "/home/sumitomo/Documents/SumiyomoAGV/sumitomo_ws/src/drivetrain/config/smartris.eds" 

